name: week3

library:
  exposed-modules:
    - Histogram
    - Hopscotch
    - LocalMaxima
  source-dirs: src
  dependencies: base, containers, split

tests:
  test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - base
      - week3
      - hspec
